version: "3.3"
services:
  mysql:
    image: "mysql:8.0"
    command: "--secure-file-priv=NULL --default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "33306:3306"
    environment:
      MYSQL_DATABASE: "playground"
      MYSQL_USER: "playground"
      MYSQL_PASSWORD: "playground"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./volume/mysql/etc/mysql:/etc/mysql"
